[package]
name = "duka-frontend"
description = "Duka's frontend"
authors = ["AogangSolang"]
version = "0.1.9"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
duka-shared = { path = "../shared" }
duka-macros = { path = "../macros" }
serde = "1.0.228"

[dev-dependencies]
criterion = "0.6.0"
rand = "0.9.1"

[[bench]]
name = "benchmark"
harness = false
