[package]
name = "duka-frontend"
description = "Duka's frontend"
authors = ["AogangSolang"]
version = "0.2.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[features]
default = ["ui"]
ui = []

[dependencies]
duka-shared = { path = "../shared" }
duka-macros = { path = "../macros" }
serde = "1.0.228"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "benchmark"
harness = false
