[package]
name = "duka-backend"
description = "Duka's backend"
authors = ["AogangSolang"]
version = "0.1.6"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
duka-shared = { path = "../shared" }
duka-macros = { path = "../macros" }
duka-gc = { path = "../gc" }
hashbrown = "0.15"
rustc-hash = "2.1"
