[package]
name = "duka-cli"
description = "Commandline interface for duka"
authors = ["Aogangsoulang"]
version = "0.1.5"
edition = "2024"

[dependencies]
duka-frontend = { path = "../frontend" }
duka-backend = { path = "../backend" }
duka-shared = { path = "../shared" }
duka-pipeline = { path = "../pipeline" }
clap = { version = "4.5.48", features = ["derive"] }
anyhow = "1.0.100"
serde = "1.0.228"
serde_json = "1.0.148"
