[package]
name = "duka-cli"
description = "Commandline interface for duka"
authors = ["Aogangsoulang"]
version = "0.1.8"
edition = "2024"

[dependencies]
duka-frontend = { path = "../frontend" }
duka-backend = { path = "../backend" }
duka-shared = { path = "../shared" }
duka-pipeline = { path = "../pipeline" }
duka-gc = { path="../gc" }
clap = { version = "4.5.48", features = ["derive"] }
serde = "1.0.228"
serde_json = "1.0.148"
miette = { version = "7.6.0", features = ["fancy", "syntect-highlighter"]}
thiserror = "2.0.18"
syntect = "5.3.0"
rustyline = "17.0.2"
