[package]
name = "duka-lib"
description = "Lib wrapper for Duka"
authors = ["AogangSolang"]
version = "0.1.0"
edition = "2024"

[dependencies]
duka-shared = { path = "../shared" }
duka-frontend = { path = "../frontend" }
duka-backend = { path = "../backend" }
duka-gc = { path = "../gc" }
duka-macros = { path = "../macros" }
toml = "0.8"
serde = { version = "1", features = ["derive"] }

[features]
docs = []

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "vm_bench"
harness = false