[package]
name = "duka-shared"
description = "Shared library for frontend and backend"
authors = ["AogangSolang"]
version = "0.1.8"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
duka-macros = { path = "../macros" }
serde = {version="1.0.228",features = ["derive"]}
unicode-ident = "1.0.18"
